version: '3'

# https://github.com/SeleniumHQ/docker-selenium

services:
  chrome-hub:
    image: selenium/standalone-chrome:3.141.59-xenon
    container_name: chrome-hub
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - 4444:4444
    network_mode: bridge