name: CI

on: [push]

jobs:
  build:
    name: Run tests against Applitools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GitHub Action for Maven & JDK 11
        uses: xlui/action-maven-cli@v1.0
      - name: execute tests
        run: mvn compile test "-Dcucumber.options=--tags @Applitools" -DAppliToolsBatchInfo=test

