name: CI

on: [push]

jobs:
  build:
    name: Run tests against Applitools
    runs-on: [linux]

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-  
      - name: GitHub Action for Maven
        uses: LucaFeger/action-maven-cli@1.0.0
      - name: execute tests
        run: mvn compile test "-Dcucumber.options=--tags @Applitools" -DAppliToolsBatchInfo=test
      

