name: CI

on: [check_run]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@master
      - name: GitHub Action for Maven & JDK 11
      - uses: xlui/action-maven-cli@v1.0
      - name: Run tests against Applitools
        run: mvn compile test "-Dcucumber.options=--tags @Applitools" -DAppliToolsBatchInfo=test

