name: CI

on: [push]

jobs:
  
  applitools:
    name: Run tests against Applitools
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master
            
      - name: Deploy container with chrome
        run: docker-compose -f docker-compose.selenium.yml up -d --build
              
#       - name: execute tests
#         run: mvn compile test "-Dcucumber.options=--tags @Applitools" -DAppliToolsBatchInfo=CI -DTestEnvironment=env-v2 -DIsRemoteInstance=true
      

